jobs:
  build:
    runs-on: windows-latest
    steps:
      # ... 其他步骤 ...
      - name: 上传构建产物
        uses: actions/upload-artifact@v4  # 从 v3 升级到 v4
        with:
          name: production-build
          path: dist/static  # 根据项目实际构建输出路径调整